version: '3.8'

services:
  app:
    build:
      context: .
    container_name: client_service
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
